### PR TITLE
Add CONTRIBUTING.md v.0.1

### PR DESCRIPTION
**Pull request by fabestah**
Add CONTRIBUTING.md v.0.1 in order to find out whether the direction in which the text goes fits the project and to give @constantinosgeorgiou (who also wants to contribute to the file) a reference point, from which he can also work on the CONTRIBUTING.md.

### CODE REVIEW

**Comment by LrnzDC3696** [comment]
Uhh, can you please resolve the conflict thanks!
Btw the contents are GREAT!!!

**Comment by fabestah** [comment]
No offense but I'm pretty sure the CONTRIBUTING.md from @constantinosgeorgiou is 100% copy paste of the atom repo, not sure if this is really the right way to do? I can't check it right now but it's either atom or some other well known repo. When I'm home by tomorrow I can send you the link.

**Comment by fabestah** [comment]
Thank you very much 💖

**Comment by LrnzDC3696** [comment]
welp... either way it's a pain to unmerge a merged pr and I'm too lazy to do that, and that may also cause conflict to other people who already the updated code... so just resolving the conflict would be fine. Thank you!

**Comment by fabestah** [comment]
Alright I can totally understand you, I just felt a little bit screwed over as I put hours in writing my own text and restructuring bits from other repos, that's why I needed to point it out. I will resolve the conflict then and add in my pieces 👍 After that I would rewrite the parts that are 100% copy paste, so we get a unique and clean CONTRIBUTING.md, does that sound good to you?
Then you would only have to accept this PR here and open a other issue afterwards instead of unmerging :)

**Comment by fabestah** [comment]
Sorry, I didn't know that deleting my repo would interfere with the already existing PR, I'm still a bit new to GitHub 😅

**Pull request closed without merging**
